"""CLI entry point."""

from __future__ import annotations

import sys
from pathlib import Path

import click


def _ensure_utf8() -> None:
    """Reconfigure stdout/stderr to UTF-8 on Windows when running interactively."""
    if sys.platform != "win32":
        return
    import io
    if hasattr(sys.stdout, "buffer"):
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    if hasattr(sys.stderr, "buffer"):
        sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

from lazyenv import __version__


@click.group(invoke_without_command=True, context_settings={"help_option_names": ["-h", "--help"]})
@click.version_option(__version__, "-V", "--version")
@click.option("--dir", "-C", "root", default=".", show_default=True,
              type=click.Path(exists=True, file_okay=False, path_type=Path),
              help="Project root to search for .env files.")
@click.option("--list", "-l", "list_files", is_flag=True, help="List .env files and exit (no TUI).")
@click.option("--diff", "-d", "diff_pair", nargs=2, type=click.Path(exists=True, path_type=Path),
              metavar="FILE1 FILE2", help="Diff two .env files and exit (no TUI).")
@click.option("--validate", "-v", "validate_pair", nargs=2, type=click.Path(exists=True, path_type=Path),
              metavar="ENV EXAMPLE", help="Validate ENV against EXAMPLE and exit.")
@click.pass_context
def main(ctx: click.Context, root: Path, list_files: bool,
         diff_pair: tuple[Path, Path] | None,
         validate_pair: tuple[Path, Path] | None) -> None:
    """lazyenv — A beautiful TUI for managing .env files.

    \b
    Examples:
        lazyenv                             # open TUI in current directory
        lazyenv -C /my/project             # open TUI in a specific directory
        lazyenv --list                     # list all .env files found
        lazyenv --diff .env .env.example
        lazyenv --validate .env .env.example
        lazyenv init                       # scaffold .env.example from .env
    """
    if ctx.invoked_subcommand is not None:
        return

    _ensure_utf8()

    if list_files:
        _cmd_list(root)
        return

    if diff_pair:
        _cmd_diff(diff_pair[0], diff_pair[1])
        return

    if validate_pair:
        _cmd_validate(validate_pair[0], validate_pair[1])
        return

    # Default: launch TUI
    from lazyenv.app import LazyEnv
    LazyEnv(root=root).run()


@main.command("init")
@click.argument("env_file", default=".env",
                type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.option("--output", "-o", default=".env.example",
              type=click.Path(dir_okay=False, path_type=Path),
              help="Output path (default: .env.example).")
@click.option("--force", "-f", is_flag=True, help="Overwrite if output already exists.")
def cmd_init(env_file: Path, output: Path, force: bool) -> None:
    """Scaffold a .env.example from an existing .env file.

    All values are blanked out; non-secret, non-empty values are preserved.
    Commit the result to your repo so teammates know which keys to set.

    \b
    Examples:
        lazyenv init                          # .env → .env.example
        lazyenv init .env.local -o .env.local.example
    """
    from lazyenv.parser import parse_file

    if output.exists() and not force:
        click.echo(f"'{output}' already exists. Use --force to overwrite.", err=True)
        raise SystemExit(1)

    env = parse_file(env_file)
    lines: list[str] = [
        f"# Generated by lazyenv from {env_file.name}\n",
        "# Fill in empty values before running the application.\n",
        "\n",
    ]

    for entry in env.entries:
        if entry.is_blank:
            lines.append("\n")
        elif entry.is_comment_line:
            lines.append(f"# {entry.comment}\n")
        elif entry.masked or entry.is_empty:
            lines.append(f"{entry.key}=\n")
        else:
            lines.append(f"{entry.key}={entry.value}\n")

    output.write_text("".join(lines), encoding="utf-8")
    click.echo(f"Generated '{output}' with {len(env)} keys.")
    click.echo("Review and fill in empty values before committing.")


# ── Non-TUI subcommands exposed as top-level options ──────────────────────────

def _cmd_list(path: Path) -> None:
    from lazyenv.parser import parse_directory
    from rich.console import Console
    from rich.table import Table

    files = parse_directory(path)
    if not files:
        click.echo("No .env files found.")
        return

    console = Console()
    table = Table(title=f"ENV files in {path}", show_header=True)
    table.add_column("File", style="cyan")
    table.add_column("Keys", justify="right")
    table.add_column("Errors", justify="right", style="red")

    for f in files:
        try:
            rel = f.path.relative_to(path)
        except ValueError:
            rel = f.path
        table.add_row(str(rel), str(len(f)), str(len(f.parse_errors)))

    console.print(table)


def _cmd_diff(file1: Path, file2: Path) -> None:
    from lazyenv.diff import diff_files
    from lazyenv.parser import parse_file
    from rich.console import Console
    from rich.table import Table
    from lazyenv.models import EntryStatus

    left = parse_file(file1)
    right = parse_file(file2)
    diff = diff_files(left, right)

    console = Console()
    table = Table(title=f"Diff: {file1.name} vs {file2.name}", show_header=True)
    table.add_column("Status", width=8)
    table.add_column("Key", style="bold")
    table.add_column(file1.name, style="dim")
    table.add_column(file2.name, style="dim")

    _colours = {
        EntryStatus.OK: "green",
        EntryStatus.MISSING: "red",
        EntryStatus.EXTRA: "green",
        EntryStatus.CHANGED: "yellow",
        EntryStatus.EMPTY: "dim",
    }

    for entry in diff.entries:
        colour = _colours[entry.status]
        table.add_row(
            f"[{colour}]{entry.status.value.upper()}[/{colour}]",
            entry.key,
            entry.left_value or "(absent)",
            entry.right_value or "(absent)",
        )

    console.print(table)
    if diff.has_issues:
        click.echo(
            f"\n{diff.missing_count} missing · {diff.extra_count} extra · {diff.changed_count} changed",
            err=True,
        )
        sys.exit(1)
    else:
        click.echo("\nFiles are in sync.")


def _cmd_validate(env_path: Path, example_path: Path) -> None:
    from lazyenv.diff import validate_against_example
    from lazyenv.parser import parse_file
    from rich.console import Console
    from lazyenv.models import EntryStatus

    env = parse_file(env_path)
    example = parse_file(example_path)
    diff = validate_against_example(env, example)

    console = Console()
    # Validation fails only on MISSING keys (keys in example but absent from env).
    # CHANGED and EXTRA are reported as warnings but don't fail.
    if diff.missing_count == 0:
        console.print(f"[green]Validation passed: {env_path.name} is valid against {example_path.name}[/green]")
        if diff.extra_count:
            console.print(f"  [yellow](note: {diff.extra_count} extra key(s) not in {example_path.name})[/yellow]")
        return

    console.print(f"[red]Validation failed: {env_path.name} vs {example_path.name}[/red]\n")
    for entry in diff.entries:
        if entry.status == EntryStatus.MISSING:
            console.print(f"  [red]MISSING[/red]  {entry.key}")
        elif entry.status == EntryStatus.EXTRA:
            console.print(f"  [yellow]EXTRA[/yellow]    {entry.key}")
    sys.exit(1)


if __name__ == "__main__":
    main()
